"""The optimizer's verdict must reach the caller — and must be believed.

`raxopt` (Mauricio, JASA 90, 282-291) ends by announcing WHY it stopped:

    1  the scaled gradient fell below tolerance      — this is a maximum
    2  the iterates stopped moving                   — this is not
    3  the last step found no lower point
    4  the iteration limit was reached
    5  five consecutive steps of maximum length

It announces it through `outputv`, which the Python binding sends to
`/dev/null`. So the verdict was computed and thrown away, and `FitResult`
reported `converged = (ifault == 0)` — "the engine did not crash", which is a
different claim altogether. On Box-Jenkins Series A that difference is 6.86 in
log-likelihood: `bugs/BUG-0012`.

The C now records what raxopt already computed (`qn_last_termcode`,
`qn_last_nit`, `qn_last_gnorm` in `csrc/internal/qnewtopt.c`) and the engine
returns it. Nothing about the algorithm changed — no criterion, no announcement,
no numerical behaviour — and `test_c_core_matches_drvus.py` holds that line.

These tests pin the three things that can rot: the verdict arrives, it is used
to decide what `converged` means, and the `.out` says the same thing the C said.
"""
import os
import warnings

import pytest

import fue

_BJ = os.path.expanduser(
    "~/Dropbox/SRC/drvus-source/1.2.01/drvus/src/Box_y_Jenkings")

_needs_bj = pytest.mark.skipif(not os.path.isdir(_BJ),
                               reason="DRVUS Box-Jenkins fixtures not present")

#: What Mauricio's own C reaches on `a1.inp`, from `SeriesA/a1.out`.
DRVUS_A1 = dict(ar=0.908683, ma=0.575839, mu=17.065225, loglik=-50.745092)


def _fit(rel, **attrs):
    _ts, m = fue.load(os.path.join(_BJ, rel))
    for k, v in attrs.items():
        setattr(m, k, v)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        m.fit()
    return m, [str(w.message) for w in caught
               if issubclass(w.category, RuntimeWarning)]


# ── the verdict arrives ────────────────────────────────────────────────────

@_needs_bj
def test_a_gradient_stop_is_reported_as_one():
    """`a2` — the textbook IMA(0,1,1) — is a genuine maximum."""
    m, warned = _fit("SeriesA/a2.inp")
    r = m._result
    assert r.termcode == 1, "termcode is not reaching Python from the C engine"
    assert r.niter > 0
    assert r.gnorm == pytest.approx(0.0, abs=1e-6)
    assert r.converged is True
    assert not warned


@_needs_bj
def test_a_step_stop_is_not_dressed_up_as_convergence():
    """BUG-0012: `a1` stops on the AR boundary by the STEP criterion, with a
    gradient that is nowhere near zero, and used to be returned as converged."""
    m, warned = _fit("SeriesA/a1.inp")
    r = m._result
    assert r.termcode == 2
    assert r.gnorm > 1e-3, (
        f"the gradient is {r.gnorm:.2e}: if it is now zero the optimizer "
        f"reached a maximum and BUG-0012 has moved")
    assert r.converged is False
    assert len(warned) == 1 and "gradiente" in warned[0]


@_needs_bj
def test_the_engine_reaches_drvus_optimum_from_a_sane_mu_seed():
    """The other half of the diagnosis, and the reason BUG-0012 is a seed
    problem and not a broken optimizer.

    `a1.inp` seeds mu = 2.5 while the mean of Series A is 17.06. Seed mu at the
    mean and fue lands on Mauricio's own answer to six decimals, by the gradient
    criterion, in a handful of iterations.
    """
    m, warned = _fit("SeriesA/a1.inp", mu0=17.0)
    r = m._result
    assert r.termcode == 1
    assert not warned
    assert m.ar[0][0] == pytest.approx(DRVUS_A1["ar"], abs=1e-5)
    assert m.ma[0][0] == pytest.approx(DRVUS_A1["ma"], abs=1e-5)
    assert m.loglik == pytest.approx(DRVUS_A1["loglik"], abs=1e-5)


@_needs_bj
@pytest.mark.parametrize("mu0", [0.0, 6.0, 12.0, 17.0, 20.0])
def test_the_trap_is_a_band_of_mu_seeds_not_the_optimizer(mu0):
    """Measured 12 August 2026: mu0 in {0, 6…20} reaches the published optimum;
    mu0 in {0.5 … 4} and 30 stops on the boundary. Half the band is asserted
    here so that "the optimizer cannot get there" stays refuted."""
    m, _warned = _fit("SeriesA/a1.inp", mu0=mu0)
    assert m.loglik == pytest.approx(DRVUS_A1["loglik"], abs=1e-4)
    assert m._result.termcode == 1


# ── the .out says what the C said ──────────────────────────────────────────

_CASES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "real_cases")


def test_the_report_carries_the_convergence_block():
    """The block is the C's, wording included (`qnewtopt.c: report()`).

    It went missing once already: `RIPC.1.out` was regenerated by the port
    (commit c1c72d7) at a time when the port could not print it, so the
    reference quietly lost two lines that 29 of the 40 C-produced references
    carry. A regression test against a reference the port itself wrote only
    holds if the reference is right.
    """
    d = os.path.join(_CASES, "PRICES/IPC/Mensual/sample_1.2002_12.2007")
    inp = os.path.join(d, "RIPC.1.inp")
    if not os.path.exists(inp):
        pytest.skip("RIPC.1 fixture not present")
    _ts, m = fue.load(inp)
    m.fit()
    out = m.write_out(inp_name="RIPC.1.inp", out_name="RIPC.1.out")
    assert "**** GRADIENT STOPPING CRITERIUM SATISFIED TO WITHIN TOLERANCE LIMITS" in out
    assert "**** CONVERGENCE OBTAINED AFTER" in out and "[GRADIENT NORM =" in out


def test_the_verdict_matches_every_preserved_c_run():
    """The strongest check available, and it is an oracle rather than a mirror.

    The `.out` files under `tests/real_cases/` were produced by the C program
    during real work and imported wholesale (commit 40b3f7b, June 2026); the
    port could not print a convergence block at all until today, so it cannot
    have written them. Each one records the criterion, the iteration count and
    the gradient norm of a run nobody can repeat.

    Measured 12 August 2026: **28 of 28 agree exactly** — same termcode, same
    number of iterations, and the same gradient norm to 1e-4 relative, including
    `Coint/R.4.out` where that norm is 116330.0394. Reproducing an iteration
    count on twenty-eight real fits is not something a wrong implementation
    does.

    It also settles what `Coint/R.4` is: not "different BLAS, different optima",
    but a fit that **never converged** — termcode 2 with a gradient of 1e5. That
    is why platforms disagree about it.
    """
    import glob
    import re

    criteria = {1: "GRADIENT STOPPING", 2: "PARAMETER STOPPING",
                3: "LAST GLOBAL STEP", 4: "ITERATION LIMIT",
                5: "FIVE CONSECUTIVE"}
    checked, mismatched = 0, []
    for out in sorted(glob.glob(os.path.join(_CASES, "**", "*.out"),
                                recursive=True)):
        inp = out[:-4] + ".inp"
        if not os.path.exists(inp):
            continue
        txt = open(out, encoding="latin-1", errors="replace").read()
        got = re.search(r"CONVERGENCE OBTAINED AFTER (\d+) ITERATIONS "
                        r"\[GRADIENT NORM = *([\d.]+)\]", txt)
        if not got:
            continue
        want_tc = next((k for k, v in criteria.items() if v in txt), None)
        want_nit, want_g = int(got.group(1)), float(got.group(2))

        _ts, m = fue.load(inp)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            m.fit()
        r = m._result
        checked += 1
        if not (r.termcode == want_tc and r.niter == want_nit
                and abs(r.gnorm - want_g) <= max(1e-4, 1e-4 * want_g)):
            mismatched.append(
                f"{os.path.relpath(out, _CASES)}: C says "
                f"tc={want_tc} nit={want_nit} |g|={want_g} — fue says "
                f"tc={r.termcode} nit={r.niter} |g|={r.gnorm:.4f}")

    if checked == 0:
        pytest.skip("no reference .out carries a convergence block")
    assert not mismatched, "\n".join(mismatched)
    assert checked >= 28, (
        f"only {checked} references were checked; the bank used to hold 28")


def test_the_reference_outs_produced_by_the_c_still_carry_it():
    """If a future edit stops emitting the block, this says how many references
    disagree rather than which single test broke."""
    import glob

    missing = []
    for p in glob.glob(os.path.join(_CASES, "**", "*.out"), recursive=True):
        txt = open(p, encoding="latin-1", errors="replace").read()
        if "Estimation method" in txt and "CONVERGENCE OBTAINED" not in txt:
            missing.append(os.path.relpath(p, _CASES))
    # Eleven of the forty lack it for reasons of their own (fuf forecast
    # reports, and the `Idem/` variants). The number is pinned so that a new
    # one appearing is noticed.
    assert len(missing) <= 11, (
        "references without the convergence block:\n  " + "\n  ".join(missing))
