#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "fue_api.h"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 10), // FueResult *()(FueModelSpec const *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // FueModelSpec const *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 20), // char const *()(int)
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 28), // void()(FueModelSpec *)
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // FueModelSpec *
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 28), // void()(FueResult *)
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // FueResult *
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 12 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // FueFactor
/* 13 */ _CFFI_OP(_CFFI_OP_ARRAY, 12), // FueFactor[8]
/* 14 */ (_cffi_opcode_t)(8),
/* 15 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // FueIntervention
/* 16 */ _CFFI_OP(_CFFI_OP_ARRAY, 15), // FueIntervention[64]
/* 17 */ (_cffi_opcode_t)(64),
/* 18 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // FueModelSpec
/* 19 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // FueResult
/* 20 */ _CFFI_OP(_CFFI_OP_POINTER, 21), // char const *
/* 21 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 22 */ _CFFI_OP(_CFFI_OP_POINTER, 23), // double *
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 24 */ _CFFI_OP(_CFFI_OP_ARRAY, 23), // double[16]
/* 25 */ (_cffi_opcode_t)(16),
/* 26 */ _CFFI_OP(_CFFI_OP_ARRAY, 4), // int[16]
/* 27 */ (_cffi_opcode_t)(16),
/* 28 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_FueFactor(FueFactor *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->order) | 0);  /* check that 'FueFactor.order' is an integer */
  { double(*tmp)[16] = &p->coefs; (void)tmp; }
  { int(*tmp)[16] = &p->coef_free; (void)tmp; }
}
struct _cffi_align_typedef_FueFactor { char x; FueFactor y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_FueIntervention(FueIntervention *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->type) | 0);  /* check that 'FueIntervention.type' is an integer */
  (void)((p->obs_index) | 0);  /* check that 'FueIntervention.obs_index' is an integer */
  (void)((p->nomega) | 0);  /* check that 'FueIntervention.nomega' is an integer */
  { double(*tmp)[16] = &p->omega; (void)tmp; }
  { int(*tmp)[16] = &p->omega_free; (void)tmp; }
  (void)((p->ndelta) | 0);  /* check that 'FueIntervention.ndelta' is an integer */
  { double(*tmp)[16] = &p->delta; (void)tmp; }
  { int(*tmp)[16] = &p->delta_free; (void)tmp; }
}
struct _cffi_align_typedef_FueIntervention { char x; FueIntervention y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_FueModelSpec(FueModelSpec *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->nobs) | 0);  /* check that 'FueModelSpec.nobs' is an integer */
  { double * *tmp = &p->data; (void)tmp; }
  (void)((p->sper) | 0);  /* check that 'FueModelSpec.sper' is an integer */
  (void)((p->numbering) | 0);  /* check that 'FueModelSpec.numbering' is an integer */
  (void)((p->begyear) | 0);  /* check that 'FueModelSpec.begyear' is an integer */
  (void)((p->begtime) | 0);  /* check that 'FueModelSpec.begtime' is an integer */
  { double *tmp = &p->boxlam; (void)tmp; }
  { double *tmp = &p->refactor; (void)tmp; }
  (void)((p->nrdiff) | 0);  /* check that 'FueModelSpec.nrdiff' is an integer */
  (void)((p->nadiff) | 0);  /* check that 'FueModelSpec.nadiff' is an integer */
  { double *tmp = &p->mu0; (void)tmp; }
  (void)((p->estimate_mu) | 0);  /* check that 'FueModelSpec.estimate_mu' is an integer */
  (void)((p->ninterventions) | 0);  /* check that 'FueModelSpec.ninterventions' is an integer */
  { FueIntervention(*tmp)[64] = &p->interventions; (void)tmp; }
  (void)((p->nar1) | 0);  /* check that 'FueModelSpec.nar1' is an integer */
  { FueFactor(*tmp)[8] = &p->ar1; (void)tmp; }
  (void)((p->nar2) | 0);  /* check that 'FueModelSpec.nar2' is an integer */
  { FueFactor(*tmp)[8] = &p->ar2; (void)tmp; }
  (void)((p->nma1) | 0);  /* check that 'FueModelSpec.nma1' is an integer */
  { FueFactor(*tmp)[8] = &p->ma1; (void)tmp; }
  (void)((p->nma2) | 0);  /* check that 'FueModelSpec.nma2' is an integer */
  { FueFactor(*tmp)[8] = &p->ma2; (void)tmp; }
  (void)((p->maxits) | 0);  /* check that 'FueModelSpec.maxits' is an integer */
  { double *tmp = &p->grtol; (void)tmp; }
  { double *tmp = &p->sptol; (void)tmp; }
  { double *tmp = &p->xitol; (void)tmp; }
  (void)((p->chkma) | 0);  /* check that 'FueModelSpec.chkma' is an integer */
  (void)((p->eml) | 0);  /* check that 'FueModelSpec.eml' is an integer */
}
struct _cffi_align_typedef_FueModelSpec { char x; FueModelSpec y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_FueResult(FueResult *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->ifault) | 0);  /* check that 'FueResult.ifault' is an integer */
  (void)((p->npar) | 0);  /* check that 'FueResult.npar' is an integer */
  { double * *tmp = &p->params; (void)tmp; }
  { double * *tmp = &p->std_errors; (void)tmp; }
  { double * *tmp = &p->cov_matrix; (void)tmp; }
  { double * *tmp = &p->residuals; (void)tmp; }
  (void)((p->nresiduals) | 0);  /* check that 'FueResult.nresiduals' is an integer */
  { double *tmp = &p->sigma2; (void)tmp; }
  { double *tmp = &p->loglik; (void)tmp; }
  { double *tmp = &p->aic; (void)tmp; }
  { double *tmp = &p->bic; (void)tmp; }
}
struct _cffi_align_typedef_FueResult { char x; FueResult y; };

static void _cffi_d_fue_defaults(FueModelSpec * x0)
{
  fue_defaults(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fue_defaults(PyObject *self, PyObject *arg0)
{
  FueModelSpec * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (FueModelSpec *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(7), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { fue_defaults(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_fue_defaults _cffi_d_fue_defaults
#endif

static FueResult * _cffi_d_fue_estimate(FueModelSpec const * x0)
{
  return fue_estimate(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fue_estimate(PyObject *self, PyObject *arg0)
{
  FueModelSpec const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  FueResult * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (FueModelSpec const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fue_estimate(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(10));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fue_estimate _cffi_d_fue_estimate
#endif

static void _cffi_d_fue_result_free(FueResult * x0)
{
  fue_result_free(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fue_result_free(PyObject *self, PyObject *arg0)
{
  FueResult * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(10), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (FueResult *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(10), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { fue_result_free(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_fue_result_free _cffi_d_fue_result_free
#endif

static char const * _cffi_d_fue_strerror(int x0)
{
  return fue_strerror(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fue_strerror(PyObject *self, PyObject *arg0)
{
  int x0;
  char const * result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fue_strerror(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(20));
  return pyresult;
}
#else
#  define _cffi_f_fue_strerror _cffi_d_fue_strerror
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "fue_defaults", (void *)_cffi_f_fue_defaults, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 6), (void *)_cffi_d_fue_defaults },
  { "fue_estimate", (void *)_cffi_f_fue_estimate, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_fue_estimate },
  { "fue_result_free", (void *)_cffi_f_fue_result_free, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 9), (void *)_cffi_d_fue_result_free },
  { "fue_strerror", (void *)_cffi_f_fue_strerror, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 3), (void *)_cffi_d_fue_strerror },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "order", offsetof(FueFactor, order),
             sizeof(((FueFactor *)0)->order),
             _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "coefs", offsetof(FueFactor, coefs),
             sizeof(((FueFactor *)0)->coefs),
             _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "coef_free", offsetof(FueFactor, coef_free),
                 sizeof(((FueFactor *)0)->coef_free),
                 _CFFI_OP(_CFFI_OP_NOOP, 26) },
  { "type", offsetof(FueIntervention, type),
            sizeof(((FueIntervention *)0)->type),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "obs_index", offsetof(FueIntervention, obs_index),
                 sizeof(((FueIntervention *)0)->obs_index),
                 _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "nomega", offsetof(FueIntervention, nomega),
              sizeof(((FueIntervention *)0)->nomega),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "omega", offsetof(FueIntervention, omega),
             sizeof(((FueIntervention *)0)->omega),
             _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "omega_free", offsetof(FueIntervention, omega_free),
                  sizeof(((FueIntervention *)0)->omega_free),
                  _CFFI_OP(_CFFI_OP_NOOP, 26) },
  { "ndelta", offsetof(FueIntervention, ndelta),
              sizeof(((FueIntervention *)0)->ndelta),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "delta", offsetof(FueIntervention, delta),
             sizeof(((FueIntervention *)0)->delta),
             _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "delta_free", offsetof(FueIntervention, delta_free),
                  sizeof(((FueIntervention *)0)->delta_free),
                  _CFFI_OP(_CFFI_OP_NOOP, 26) },
  { "nobs", offsetof(FueModelSpec, nobs),
            sizeof(((FueModelSpec *)0)->nobs),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "data", offsetof(FueModelSpec, data),
            sizeof(((FueModelSpec *)0)->data),
            _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "sper", offsetof(FueModelSpec, sper),
            sizeof(((FueModelSpec *)0)->sper),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "numbering", offsetof(FueModelSpec, numbering),
                 sizeof(((FueModelSpec *)0)->numbering),
                 _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "begyear", offsetof(FueModelSpec, begyear),
               sizeof(((FueModelSpec *)0)->begyear),
               _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "begtime", offsetof(FueModelSpec, begtime),
               sizeof(((FueModelSpec *)0)->begtime),
               _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "boxlam", offsetof(FueModelSpec, boxlam),
              sizeof(((FueModelSpec *)0)->boxlam),
              _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "refactor", offsetof(FueModelSpec, refactor),
                sizeof(((FueModelSpec *)0)->refactor),
                _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "nrdiff", offsetof(FueModelSpec, nrdiff),
              sizeof(((FueModelSpec *)0)->nrdiff),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "nadiff", offsetof(FueModelSpec, nadiff),
              sizeof(((FueModelSpec *)0)->nadiff),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "mu0", offsetof(FueModelSpec, mu0),
           sizeof(((FueModelSpec *)0)->mu0),
           _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "estimate_mu", offsetof(FueModelSpec, estimate_mu),
                   sizeof(((FueModelSpec *)0)->estimate_mu),
                   _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "ninterventions", offsetof(FueModelSpec, ninterventions),
                      sizeof(((FueModelSpec *)0)->ninterventions),
                      _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "interventions", offsetof(FueModelSpec, interventions),
                     sizeof(((FueModelSpec *)0)->interventions),
                     _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "nar1", offsetof(FueModelSpec, nar1),
            sizeof(((FueModelSpec *)0)->nar1),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "ar1", offsetof(FueModelSpec, ar1),
           sizeof(((FueModelSpec *)0)->ar1),
           _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "nar2", offsetof(FueModelSpec, nar2),
            sizeof(((FueModelSpec *)0)->nar2),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "ar2", offsetof(FueModelSpec, ar2),
           sizeof(((FueModelSpec *)0)->ar2),
           _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "nma1", offsetof(FueModelSpec, nma1),
            sizeof(((FueModelSpec *)0)->nma1),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "ma1", offsetof(FueModelSpec, ma1),
           sizeof(((FueModelSpec *)0)->ma1),
           _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "nma2", offsetof(FueModelSpec, nma2),
            sizeof(((FueModelSpec *)0)->nma2),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "ma2", offsetof(FueModelSpec, ma2),
           sizeof(((FueModelSpec *)0)->ma2),
           _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "maxits", offsetof(FueModelSpec, maxits),
              sizeof(((FueModelSpec *)0)->maxits),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "grtol", offsetof(FueModelSpec, grtol),
             sizeof(((FueModelSpec *)0)->grtol),
             _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "sptol", offsetof(FueModelSpec, sptol),
             sizeof(((FueModelSpec *)0)->sptol),
             _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "xitol", offsetof(FueModelSpec, xitol),
             sizeof(((FueModelSpec *)0)->xitol),
             _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "chkma", offsetof(FueModelSpec, chkma),
             sizeof(((FueModelSpec *)0)->chkma),
             _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "eml", offsetof(FueModelSpec, eml),
           sizeof(((FueModelSpec *)0)->eml),
           _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "ifault", offsetof(FueResult, ifault),
              sizeof(((FueResult *)0)->ifault),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "npar", offsetof(FueResult, npar),
            sizeof(((FueResult *)0)->npar),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "params", offsetof(FueResult, params),
              sizeof(((FueResult *)0)->params),
              _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "std_errors", offsetof(FueResult, std_errors),
                  sizeof(((FueResult *)0)->std_errors),
                  _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "cov_matrix", offsetof(FueResult, cov_matrix),
                  sizeof(((FueResult *)0)->cov_matrix),
                  _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "residuals", offsetof(FueResult, residuals),
                 sizeof(((FueResult *)0)->residuals),
                 _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "nresiduals", offsetof(FueResult, nresiduals),
                  sizeof(((FueResult *)0)->nresiduals),
                  _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "sigma2", offsetof(FueResult, sigma2),
              sizeof(((FueResult *)0)->sigma2),
              _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "loglik", offsetof(FueResult, loglik),
              sizeof(((FueResult *)0)->loglik),
              _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "aic", offsetof(FueResult, aic),
           sizeof(((FueResult *)0)->aic),
           _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "bic", offsetof(FueResult, bic),
           sizeof(((FueResult *)0)->bic),
           _CFFI_OP(_CFFI_OP_NOOP, 23) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$FueFactor", 12, _CFFI_F_CHECK_FIELDS,
    sizeof(FueFactor), offsetof(struct _cffi_align_typedef_FueFactor, y), 0, 3 },
  { "$FueIntervention", 15, _CFFI_F_CHECK_FIELDS,
    sizeof(FueIntervention), offsetof(struct _cffi_align_typedef_FueIntervention, y), 3, 8 },
  { "$FueModelSpec", 18, _CFFI_F_CHECK_FIELDS,
    sizeof(FueModelSpec), offsetof(struct _cffi_align_typedef_FueModelSpec, y), 11, 28 },
  { "$FueResult", 19, _CFFI_F_CHECK_FIELDS,
    sizeof(FueResult), offsetof(struct _cffi_align_typedef_FueResult, y), 39, 11 },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "FueFactor", 12 },
  { "FueIntervention", 15 },
  { "FueModelSpec", 18 },
  { "FueResult", 19 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  4,  /* num_globals */
  4,  /* num_struct_unions */
  0,  /* num_enums */
  4,  /* num_typenames */
  NULL,  /* no includes */
  29,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__fue_engine(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__fue_engine(void) { return NULL; }
#  else
     init_fue_engine(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__fue_engine(void)
{
  return _cffi_init("fue._fue_engine", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_fue_engine(void)
{
  _cffi_init("fue._fue_engine", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
